Section "InputClass"
    Identifier "libinput pointer catchall"
    MatchIsPointer "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "0"
 EndSection

Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchDevicePath "/dev/input/event*"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"
    Option "NaturalScrolling" "on"
    Option "ClickMethod" "clickfinger"
    Option "DisableWhileTyping" "on"
 EndSection

