#!/usr/bin/env bash

firefox &
sleep 1
xdotool key "Super_L+b"
sleep 0.2
xdotool key "Super_L+Return"
sleep 0.2
xdotool key "Super_L+v"
sleep 0.2
xdotool key "Super_L+Return"
sleep 0.1
xdotool key "Super_L+r"
sleep 0.1
xdotool key "h" --repeat 3 --repeat-delay 100
sleep 0.1
xdotool key "Escape"
